name: Update hash

on:
  workflow_dispatch:
  schedule:
    - cron: "33 8 * * *"

jobs:
  update-hash:
    name: update-hash
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update hash
        run: nix run nixpkgs#update-nix-fetchgit ${GITHUB_WORKSPACE}/default.nix

      - name: Check if there are changes
        run: |
          echo has_changes=$(git status --porcelain | wc -l) >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        if: ${{ env.has_changes != 0 }}
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update ro.am hash
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: chore/bump-hash
          title: "Chore: Bump hash of ro.am"
          body: |
            Bump hash of ro.am
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          assignees: xgroleau
          reviewers: xgroleau
