name: Update hash

on:
  workflow_dispatch:
  schedule:
    - cron: "33 8 * * *"

jobs:
  update-hash:
    name: update-hash
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update roam URL
        run: |
          # Yes, we just get the "source" variable from PKGBUILD instead of using the AUR rest api to fetch the version
          # So if roam change the base URL, it will still work
          git clone https://aur.archlinux.org/roam ${RUNNER_TEMP}/roam
          echo "echo ROAM_URL=\$source" >> ${RUNNER_TEMP}/roam/PKGBUILD
          echo "echo ROAM_VERSION=\$pkgver" >> ${RUNNER_TEMP}/roam/PKGBUILD

          # make it executable, run it and get the variables
          chmod +x ${RUNNER_TEMP}/roam/PKGBUILD
          export $(${RUNNER_TEMP}/roam/PKGBUILD | xargs)


          # A bit of perl cancer to update the variables
          perl -0777 -i -pe '$var = $ENV{ROAM_URL}; s/url\s*=\s*\"[^\"\n\r;]+\";/url = "$var";/g' default.nix
          perl -0777 -i -pe '$var = $ENV{ROAM_VERSION}; s/version\s*=\s*\"[^\"\n\r;]+\";/version = "$var";/g' default.nix

          # Format files as needed
          nix fmt
      - name: Update hash
        run: nix run nixpkgs#update-nix-fetchgit ${GITHUB_WORKSPACE}/default.nix

      - name: Check if there are changes
        run: |
          echo has_changes=$(git status --porcelain | wc -l) >> $GITHUB_ENV

      - uses: tibdex/github-app-token@v2
        id: create_token
        if: ${{ env.has_changes != 0 }}
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        if: ${{ env.has_changes != 0 }}
        with:
          token: ${{ steps.create_token.outputs.token }}
          commit-message: Update ro.am hash
          branch: chore/bump-hash
          title: "Chore: Bump hash of ro.am"
          body: |
            Bump hash of ro.am
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          assignees: xgroleau
          reviewers: xgroleau
